### ISSUE TITLE
/system/bin/sh: dpm: not found

### ISSUE THREAD

**Issue by 5605006** [hyongbai/AirFrozenGranter#1]
出现/system/bin/sh: dpm: not found，是不是没有busybox呀

**Comment by 5605006** [comment]
还有，adb命令执行后，重启需要重新执行吗

**Comment by hyongbai** [comment]
@5605006 busybox不一定有dpm这个指令，这个是android里面的DevicePolicyManager的缩写。执行之后最好重启下。
