### ISSUE TITLE
添加DPM之后无法卸载或者更改。。

### ISSUE THREAD

**Issue by ljm625** [hyongbai/AirFrozenGranter#2]
添加DPM之后无法卸载。。。
adb shell dpm remove-active-admin me.yourbay.airfrozen/.main.core.mgmt.MDeviceAdminReceiver
这条命令也会exception，只能重置手机么。。。

**Comment by hyongbai** [comment]
@ljm625 是的。目前只能root或者factory reset。如果大家有发现更好的方案的话也欢迎来提哈。

**Comment by yougg** [comment]
不知道这个[方式](https://stackoverflow.com/questions/5387582/how-to-remove-an-app-with-active-device-admin-enabled-on-android)是否可行。

或者在应用内调用这个接口[clearDeviceOwnerApp](https://developer.android.google.cn/reference/android/app/admin/DevicePolicyManager.html#clearDeviceOwnerApp(java.lang.String)) ?
